# Generated by Scripts/release.sh in the snippety-migrate repository. Do not edit by hand.
class SnippetyMigrate < Formula
  desc "Convert snippets from other text expansion apps into Snippety's backup JSON"
  homepage "https://snippety.app"
  url "https://github.com/snippety-app/snippety-migrate/releases/download/v1.1.0/snippety-migrate-1.1.0-macos-universal.tar.gz"
  version "1.1.0"
  sha256 "395a899657819e6112b60d5265aa8f63298b58f89a4a8e0d2dfd0980742b62d3"

  # Lets `brew livecheck` and `brew bump-formula-pr` see new releases as they are published.
  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on macos: :ventura

  def install
    bin.install "snippety-migrate"
  end

  test do
    assert_match "textexpander", shell_output("#{bin}/snippety-migrate formats")
  end
end
