# Generated by Scripts/release.sh in the snippety-migrator repository. Do not edit by hand.
#
# NOT PUBLISHED YET: v1.0.0 has no release, so the url below 404s and the checksum is a local build's.
# The first `Scripts/release.sh` run rewrites both from the published artifact — that run is what
# makes this formula work. Everything else here is final.
class SnippetyMigrate < Formula
  desc "Convert snippets from other text expansion apps into Snippety's backup JSON"
  homepage "https://snippety.app"
  url "https://github.com/snippety-app/snippety-migrator/releases/download/v1.0.0/snippety-migrate-1.0.0-macos-universal.tar.gz"
  version "1.0.0"
  sha256 "ab177bc30c96fb542889c260b6e5ae23ab8fc36ef8e62b25488785e5c5d988c3"

  # Lets `brew livecheck` and `brew bump-formula-pr` see new releases as they are published.
  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on macos: :ventura

  def install
    bin.install "snippety-migrate"
  end

  test do
    assert_match "textexpander", shell_output("#{bin}/snippety-migrate formats")
  end
end
