# Generated by Scripts/release.sh in the snippety-migrate repository. Do not edit by hand.
class SnippetyMigrate < Formula
  desc "Convert snippets from other text expansion apps into Snippety's backup JSON"
  homepage "https://snippety.app"
  url "https://github.com/snippety-app/snippety-migrate/releases/download/v1.0.1/snippety-migrate-1.0.1-macos-universal.tar.gz"
  version "1.0.1"
  sha256 "3461dfe22cd5b1cd3ddafcbfc423c2b829c5c4e46bcb8c4332e293241178e130"

  # Lets `brew livecheck` and `brew bump-formula-pr` see new releases as they are published.
  livecheck do
    url :stable
    strategy :github_latest
  end

  depends_on macos: :ventura

  def install
    bin.install "snippety-migrate"
  end

  test do
    assert_match "textexpander", shell_output("#{bin}/snippety-migrate formats")
  end
end
